from typing import Any, Dict, List, Optional
from datetime import datetime


class SharedMemory:

    def __init__(self):
        """
        Stores information shared between agents
        during a single application execution.
        """

        self._data: Dict[str, Any] = {}

        self._execution_log: List[Dict[str, Any]] = []

    # ======================================================
    # STORE DATA
    # ======================================================

    def set(
        self,
        key: str,
        value: Any
    ):
        """
        Store information in shared memory.
        """

        self._data[key] = value

    # ======================================================
    # GET DATA
    # ======================================================

    def get(
        self,
        key: str,
        default: Any = None
    ) -> Any:
        """
        Retrieve information from shared memory.
        """

        return self._data.get(
            key,
            default
        )

    # ======================================================
    # CHECK DATA
    # ======================================================

    def has(
        self,
        key: str
    ) -> bool:
        """
        Check whether a key exists.
        """

        return key in self._data

    # ======================================================
    # DELETE DATA
    # ======================================================

    def delete(
        self,
        key: str
    ):
        """
        Remove a value from shared memory.
        """

        if key in self._data:
            del self._data[key]

    # ======================================================
    # GET ALL DATA
    # ======================================================

    def get_all(self) -> Dict[str, Any]:
        """
        Return a copy of all shared information.
        """

        return self._data.copy()

    # ======================================================
    # STORE USER REQUEST
    # ======================================================

    def set_user_request(
        self,
        user_request: str
    ):
        """
        Store the original user request.
        """

        self.set(
            "user_request",
            user_request
        )

    # ======================================================
    # GET USER REQUEST
    # ======================================================

    def get_user_request(
        self
    ) -> Optional[str]:

        """
        Retrieve the original user request.
        """

        return self.get(
            "user_request"
        )

    # ======================================================
    # STORE AGENT OUTPUT
    # ======================================================

    def set_agent_output(
        self,
        agent_name: str,
        output: Any
    ):
        """
        Store output generated by an agent.

        Example:

        Research Agent
            ↓
        research_output
        """

        key = self._create_agent_output_key(
            agent_name
        )

        self.set(
            key,
            output
        )

    # ======================================================
    # GET AGENT OUTPUT
    # ======================================================

    def get_agent_output(
        self,
        agent_name: str
    ) -> Any:
        """
        Retrieve the output of a particular agent.
        """

        key = self._create_agent_output_key(
            agent_name
        )

        return self.get(
            key
        )

    # ======================================================
    # GET ALL AGENT OUTPUTS
    # ======================================================

    def get_all_agent_outputs(
        self
    ) -> Dict[str, Any]:
        """
        Return all stored agent outputs.

        Only memory keys ending with '_output'
        are considered agent outputs.
        """

        outputs = {}

        for key, value in self._data.items():

            if not key.endswith("_output"):
                continue

            if key == "planner_output":
                agent_name = "Planner Agent"

            elif key == "research_output":
                agent_name = "Research Agent"

            elif key == "transportation_output":
                agent_name = "Transportation Agent"

            elif key == "accommodation_output":
                agent_name = "Accommodation Agent"

            elif key == "itinerary_output":
                agent_name = "Itinerary Agent"

            elif key == "budget_output":
                agent_name = "Budget Agent"

            elif key == "review_output":
                agent_name = "Review Agent"

            elif key == "response_output":
                agent_name = "Response Agent"

            else:
                agent_name = (
                    key
                    .replace("_output", "")
                    .replace("_", " ")
                    .title()
                    + " Agent"
                )

            outputs[agent_name] = value

        return outputs

    # ======================================================
    # CREATE AGENT OUTPUT KEY
    # ======================================================

    def _create_agent_output_key(
        self,
        agent_name: str
    ) -> str:
        """
        Convert an agent name into a consistent
        memory key.

        Examples:

        Research Agent
            ↓
        research_output

        Transportation Agent
            ↓
        transportation_output
        """

        normalized_name = (
            agent_name
            .strip()
            .lower()
        )

        if normalized_name.endswith(
            " agent"
        ):
            normalized_name = (
                normalized_name[
                    :-len(" agent")
                ]
            )

        normalized_name = (
            normalized_name
            .replace(" ", "_")
        )

        return (
            f"{normalized_name}_output"
        )

    # ======================================================
    # ADD EXECUTION RECORD
    # ======================================================

    def add_execution_record(
        self,
        agent: str,
        task: str,
        status: str,
        output: Any = None,
        execution_time: Optional[float] = None
    ):
        """
        Store information about an agent execution.
        """

        record = {
            "agent": agent,
            "task": task,
            "status": status,
            "output": output,
            "execution_time": execution_time,
            "timestamp": datetime.now().isoformat()
        }

        self._execution_log.append(
            record
        )

    # ======================================================
    # UPDATE EXECUTION RECORD
    # ======================================================

    def update_execution_record(
        self,
        agent: str,
        status: str,
        output: Any = None,
        execution_time: Optional[float] = None
    ):
        """
        Update the latest execution record
        for an agent.
        """

        for record in reversed(
            self._execution_log
        ):

            if (
                record.get("agent") == agent
                and record.get("status") == "running"
            ):

                record["status"] = status
                record["output"] = output
                record["execution_time"] = execution_time

                return

    # ======================================================
    # GET EXECUTION LOG
    # ======================================================

    def get_execution_log(
        self
    ) -> List[Dict[str, Any]]:

        """
        Return the complete execution history.
        """

        return self._execution_log.copy()

    # ======================================================
    # CLEAR MEMORY
    # ======================================================

    def clear(self):
        """
        Clear all stored information.

        Called before starting a new
        travel planning request.
        """

        self._data.clear()

        self._execution_log.clear()