import os
import re
import time
from typing import Any, Dict, List, Optional

import requests
from dotenv import load_dotenv
from app.core.agent_registry import AgentRegistry
from app.memory.shared_memory import SharedMemory


class Orchestrator:

    def __init__(
        self,
        registry: AgentRegistry,
        memory: SharedMemory
    ):
        """
        Coordinates all agents using the execution plan
        generated by the Planner Agent.
        """

        self.registry = registry
        self.memory = memory

        # --------------------------------------------------
        # PEXELS IMAGE CONFIGURATION
        # --------------------------------------------------
        # Destination images are fetched dynamically from Pexels.
        # No destinations.json or local destination image files are
        # required. The API key stays on the backend in .env.
        load_dotenv()

        self.pexels_api_key = os.getenv("PEXELS_API_KEY", "").strip()
        self.pexels_search_url = "https://api.pexels.com/v1/search"
        self.pexels_image_count = 6


    # ======================================================
    # MAIN WORKFLOW
    # ======================================================

    def run(
        self,
        user_request: str
    ) -> Dict[str, Any]:

        # --------------------------------------------------
        # RESET MEMORY
        # --------------------------------------------------

        self.memory.clear()

        # --------------------------------------------------
        # PRESERVE ORIGINAL REQUEST
        # --------------------------------------------------

        self.memory.set_user_request(user_request)

        self.memory.set(
            "original_user_request",
            user_request
        )

        self.memory.set(
            "user_request",
            user_request
        )

        print("\n")
        print("=" * 70)
        print("🚀 ORCHESTRATOR STARTED")
        print("=" * 70)
        print("👤 USER REQUEST:")
        print(user_request)
        print("=" * 70)

        # ==================================================
        # STEP 1
        # PLANNER AGENT
        # ==================================================

        print("\n")
        print("🧠 STEP 1: Running Planner Agent...")
        print("-" * 70)

        planner_result = self._execute_agent(
            agent_name="Planner Agent",
            task=user_request,
            context={
                "user_request": user_request,
                "original_user_request": user_request,
                "available_agents": (
                    self.registry
                    .get_available_agents_for_planner()
                )
            }
        )

        # --------------------------------------------------
        # IMPORTANT:
        #
        # BaseAgent.execute() returns:
        #
        # {
        #     "agent": "...",
        #     "status": "...",
        #     "output": ACTUAL_AGENT_OUTPUT
        # }
        #
        # Therefore we explicitly unwrap it here.
        # --------------------------------------------------

        if not isinstance(planner_result, dict):

            return self._failure_response(
                message=(
                    "Planner Agent returned an "
                    "invalid response."
                ),
                planner_output=planner_result
            )

        # --------------------------------------------------
        # Check Planner execution status
        # --------------------------------------------------

        planner_status = planner_result.get(
            "status"
        )

        if planner_status != "completed":

            return self._failure_response(
                message=(
                    "Planner Agent execution failed."
                ),
                planner_output=planner_result
            )

        # --------------------------------------------------
        # Extract actual Planner output
        # --------------------------------------------------

        planner_output = planner_result.get(
            "output"
        )

        # --------------------------------------------------
        # Defensive unwrapping
        #
        # Handles accidental double wrapping:
        #
        # output:
        # {
        #   "agent": "Planner Agent",
        #   "status": "completed",
        #   "output": {
        #       "request_analysis": ...,
        #       "subtasks": ...
        #   }
        # }
        # --------------------------------------------------

        planner_output = self._unwrap_agent_output(
            planner_output
        )

        print("\n")
        print("🔎 PLANNER OUTPUT TYPE:")
        print(type(planner_output))

        print("🔎 PLANNER OUTPUT:")
        print(planner_output)

        # --------------------------------------------------
        # Validate Planner output
        # --------------------------------------------------

        if not isinstance(
            planner_output,
            dict
        ):

            return self._failure_response(
                message=(
                    "Planner Agent did not return "
                    "a valid planning object."
                ),
                planner_output=planner_output
            )

        if "error" in planner_output:

            return self._failure_response(
                message=(
                    "Planner Agent returned an error."
                ),
                planner_output=planner_output
            )

        # --------------------------------------------------
        # Store Planner output
        # --------------------------------------------------

        self.memory.set(
            "planner_output",
            planner_output
        )

        # ==================================================
        # REQUEST ANALYSIS
        # ==================================================

        request_analysis = planner_output.get(
            "request_analysis",
            {}
        )

        if not isinstance(
            request_analysis,
            dict
        ):

            request_analysis = {}

        self.memory.set(
            "request_analysis",
            request_analysis
        )

        # ==================================================
        # DESTINATION IMAGE DATA
        # ==================================================
        # Get the destination dynamically from the Planner output
        # and attach matching image metadata to shared memory.
        # Nothing is hardcoded to Ooty or any other destination.
        destination_image_data = self._get_destination_image_data(
            planner_output=planner_output,
            request_analysis=request_analysis,
            user_request=user_request
        )

        self.memory.set(
            "destination_image_data",
            destination_image_data
        )

        print("\n")
        print("🖼️ DESTINATION IMAGE DATA:")
        print(destination_image_data)

        # --------------------------------------------------
        # Display request analysis
        # --------------------------------------------------

        print("\n")
        print("✅ PLANNER COMPLETED")
        print("-" * 70)

        print("📋 REQUEST ANALYSIS:")
        print(request_analysis)

        # ==================================================
        # STEP 2
        # GET SUBTASKS
        # ==================================================

        subtasks = planner_output.get(
            "subtasks"
        )

        # --------------------------------------------------
        # IMPORTANT:
        #
        # Do NOT silently replace an invalid subtasks value
        # with another object.
        # --------------------------------------------------

        if not isinstance(
            subtasks,
            list
        ):

            print("\n❌ INVALID PLANNER SUBTASKS")
            print(
                "Planner output type:",
                type(planner_output)
            )
            print(
                "Planner output:",
                planner_output
            )

            return self._failure_response(
                message=(
                    "Planner Agent did not generate "
                    "a valid subtasks list."
                ),
                planner_output=planner_output
            )

        if len(subtasks) == 0:

            print("\n❌ EMPTY PLANNER SUBTASKS")

            return self._failure_response(
                message=(
                    "Planner Agent generated an "
                    "empty execution plan."
                ),
                planner_output=planner_output
            )

        # --------------------------------------------------
        # Validate execution plan
        # --------------------------------------------------

        validation_error = (
            self._validate_execution_plan(
                subtasks
            )
        )

        if validation_error:

            return self._failure_response(
                message=validation_error,
                planner_output=planner_output
            )

        # --------------------------------------------------
        # Sort subtasks
        # --------------------------------------------------

        subtasks = sorted(
            subtasks,
            key=lambda item: item["step"]
        )

        # --------------------------------------------------
        # Store normalized subtasks
        # --------------------------------------------------

        planner_output["subtasks"] = subtasks

        self.memory.set(
            "planner_output",
            planner_output
        )

        # ==================================================
        # DISPLAY EXECUTION PLAN
        # ==================================================

        print("\n")
        print("=" * 70)
        print("📋 DYNAMIC EXECUTION PLAN")
        print("=" * 70)

        for subtask in subtasks:

            print(
                f"STEP {subtask['step']} "
                f"→ {subtask['agent']}"
            )

            print(
                f"   Task: {subtask['task']}"
            )

            print(
                f"   Depends on: "
                f"{subtask.get('depends_on', [])}"
            )

            print(
                f"   Parallelizable: "
                f"{subtask.get('parallelizable', False)}"
            )

            print()

        # ==================================================
        # STEP 3
        # EXECUTE AGENTS
        # ==================================================

        completed_steps: Dict[
            int,
            Dict[str, Any]
        ] = {}

        pending_tasks = list(
            subtasks
        )

        print("=" * 70)
        print("🤖 STARTING MULTI-AGENT EXECUTION")
        print("=" * 70)

        while pending_tasks:

            progress_made = False

            # --------------------------------------------------
            # Process pending tasks
            # --------------------------------------------------

            for subtask in list(
                pending_tasks
            ):

                step = subtask["step"]

                agent_name = subtask["agent"]

                subtask_task = subtask["task"]

                dependencies = subtask.get(
                    "depends_on",
                    []
                )

                # --------------------------------------------------
                # Wait for dependencies
                # --------------------------------------------------

                if not self._dependencies_completed(
                    dependencies,
                    completed_steps
                ):
                    continue

                # --------------------------------------------------
                # Check agent registration
                # --------------------------------------------------

                if not self.registry.has_agent(
                    agent_name
                ):

                    error_output = {
                        "error": (
                            f"Agent '{agent_name}' "
                            "is not registered."
                        )
                    }

                    self.memory.add_execution_record(
                        agent=agent_name,
                        task=subtask_task,
                        status="failed",
                        output=error_output
                    )

                    return self._failure_response(
                        message=(
                            f"Planner selected an "
                            f"unregistered agent: "
                            f"{agent_name}"
                        ),
                        planner_output=planner_output,
                        failed_agent=agent_name,
                        failed_step=step,
                        agent_output=error_output
                    )

                # ==================================================
                # BUILD CONTEXT
                # ==================================================

                agent_context = (
                    self._build_context()
                )

                # --------------------------------------------------
                # Preserve user request
                # --------------------------------------------------

                agent_context[
                    "user_request"
                ] = user_request

                agent_context[
                    "original_user_request"
                ] = user_request

                # --------------------------------------------------
                # Preserve request analysis
                # --------------------------------------------------

                agent_context[
                    "request_analysis"
                ] = request_analysis

                # --------------------------------------------------
                # Destination image information
                # --------------------------------------------------
                agent_context[
                    "destination_image_data"
                ] = destination_image_data

                # ==================================================
                # DEPENDENCY OUTPUTS
                # ==================================================

                dependency_outputs = {}

                for dependency in dependencies:

                    dependency_data = (
                        completed_steps.get(
                            dependency
                        )
                    )

                    if not dependency_data:
                        continue

                    dependency_agent = (
                        dependency_data.get(
                            "agent"
                        )
                    )

                    dependency_output = (
                        dependency_data.get(
                            "output"
                        )
                    )

                    if dependency_agent:

                        dependency_outputs[
                            dependency_agent
                        ] = dependency_output

                agent_context[
                    "dependency_outputs"
                ] = dependency_outputs

                # ==================================================
                # ALL COMPLETED OUTPUTS
                # ==================================================

                all_completed_outputs = {}

                for (
                    completed_step,
                    completed_data
                ) in completed_steps.items():

                    completed_agent = (
                        completed_data.get(
                            "agent"
                        )
                    )

                    completed_output = (
                        completed_data.get(
                            "output"
                        )
                    )

                    if completed_agent:

                        all_completed_outputs[
                            completed_agent
                        ] = completed_output

                agent_context[
                    "completed_agent_outputs"
                ] = all_completed_outputs

                # ==================================================
                # ENRICH TASK
                # ==================================================

                enriched_task = (
                    "Original User Request:\n"
                    f"{user_request}\n\n"

                    "Planner Request Analysis:\n"
                    f"{request_analysis}\n\n"

                    "Destination Image Data:\n"
                    f"{destination_image_data}\n\n"

                    "Dependency Agent Outputs:\n"
                    f"{dependency_outputs}\n\n"

                    "All Completed Agent Outputs:\n"
                    f"{all_completed_outputs}\n\n"

                    "Assigned Subtask:\n"
                    f"{subtask_task}"
                )

                # ==================================================
                # DISPLAY
                # ==================================================

                print("\n")
                print("=" * 70)
                print(
                    f"🤖 STEP {step}: "
                    f"{agent_name}"
                )
                print("=" * 70)

                print(
                    f"📌 TASK: {subtask_task}"
                )

                print(
                    f"🔗 DEPENDENCIES: "
                    f"{dependencies}"
                )

                # ==================================================
                # EXECUTE AGENT
                # ==================================================

                result = self._execute_agent(
                    agent_name=agent_name,
                    task=enriched_task,
                    context=agent_context
                )

                # --------------------------------------------------
                # Extract actual output
                # --------------------------------------------------

                agent_output = self._unwrap_agent_output(
                    result.get(
                        "output",
                        result
                    )
                )

                # ==================================================
                # CHECK FAILURE
                # ==================================================

                if result.get("status") != "completed":

                    print(
                        f"\n❌ {agent_name} FAILED"
                    )

                    return self._failure_response(
                        message=(
                            f"{agent_name} failed "
                            f"during execution."
                        ),
                        planner_output=planner_output,
                        failed_agent=agent_name,
                        failed_step=step,
                        agent_output=agent_output
                    )

                if not self._is_valid_agent_output(
                    agent_output
                ):

                    print(
                        f"\n❌ {agent_name} returned "
                        "an invalid output."
                    )

                    return self._failure_response(
                        message=(
                            f"{agent_name} returned "
                            "an invalid output."
                        ),
                        planner_output=planner_output,
                        failed_agent=agent_name,
                        failed_step=step,
                        agent_output=agent_output
                    )

                # ==================================================
                # STORE OUTPUT
                # ==================================================

                self.memory.set_agent_output(
                    agent_name,
                    agent_output
                )

                self.memory.set(
                    f"step_{step}_output",
                    agent_output
                )

                context_key = (
                    self._agent_context_key(
                        agent_name
                    )
                )

                if context_key:

                    self.memory.set(
                        context_key,
                        agent_output
                    )

                # ==================================================
                # MARK COMPLETED
                # ==================================================

                completed_steps[
                    step
                ] = {
                    "agent": agent_name,
                    "task": subtask_task,
                    "output": agent_output
                }

                # ==================================================
                # DISPLAY OUTPUT
                # ==================================================

                print("\n")
                print(
                    f"✅ {agent_name} COMPLETED"
                )

                print(
                    f"⏱️ Execution time: "
                    f"{result.get('execution_time', 0)}s"
                )

                print(
                    "📤 OUTPUT:"
                )

                print(agent_output)

                print("-" * 70)

                pending_tasks.remove(
                    subtask
                )

                progress_made = True

            # ==================================================
            # DEADLOCK PROTECTION
            # ==================================================

            if not progress_made:

                print("\n❌ EXECUTION STOPPED")

                for task in pending_tasks:

                    print(
                        f"Step {task.get('step')} "
                        f"→ {task.get('agent')} "
                        f"depends on "
                        f"{task.get('depends_on')}"
                    )

                return self._failure_response(
                    message=(
                        "The Planner Agent generated "
                        "an execution plan with "
                        "unresolvable dependencies."
                    ),
                    planner_output=planner_output
                )

        # ==================================================
        # STEP 4
        # FINAL RESPONSE
        # ==================================================

        final_output = (
            self.memory.get_agent_output(
                "Response Agent"
            )
        )

        response_agent_selected = any(
            subtask.get("agent")
            == "Response Agent"
            for subtask in subtasks
        )

        if response_agent_selected:

            if not self._is_valid_agent_output(
                final_output
            ):

                return self._failure_response(
                    message=(
                        "Response Agent did not "
                        "produce a valid final output."
                    ),
                    planner_output=planner_output,
                    failed_agent="Response Agent",
                    agent_output=final_output
                )

        # ==================================================
        # FINAL RESULT
        # ==================================================

        all_agent_outputs = (
            self._get_agent_outputs()
        )

        print("\n")
        print("=" * 70)
        print("🎉 ORCHESTRATOR COMPLETED")
        print("=" * 70)

        print(
            f"✅ Total agents executed: "
            f"{len(all_agent_outputs)}"
        )

        print("\n")
        print("🏁 FINAL RESPONSE")
        print("=" * 70)

        print(final_output)

        print("=" * 70)

        return {
            "success": True,
            "user_request": user_request,
            "request_analysis": request_analysis,
            "planner_output": planner_output,
            "destination_image_data": destination_image_data,
            "agent_outputs": all_agent_outputs,
            "completed_steps": completed_steps,
            "execution_log": (
                self.memory
                .get_execution_log()
            ),
            "final_output": final_output
        }

    # ======================================================
    # DESTINATION IMAGE DATA - PEXELS
    # ======================================================

    def _get_destination_image_data(
        self,
        planner_output: Any,
        request_analysis: Any,
        user_request: str
    ) -> Dict[str, Any]:
        """
        Dynamically identify the destination and fetch travel images
        from Pexels.

        This method does not use destinations.json and does not contain
        destination-specific hardcoding.
        """

        empty_result = {
            "available": False,
            "destination": None,
            "images": [],
            "attractions": [],
            "search_queries": [],
            "image_count": 0,
            "source": "Pexels",
            "message": "No destination images available."
        }

        # --------------------------------------------------
        # FIND DESTINATION
        # --------------------------------------------------
        destination = self._extract_destination(request_analysis)

        if not destination:
            destination = self._extract_destination(planner_output)

        if not destination:
            destination = self._extract_destination_from_text(
                user_request
            )

        if not destination:
            return {
                **empty_result,
                "message": (
                    "The destination could not be identified from "
                    "the Planner output or user request."
                )
            }

        destination = destination.strip()

        if not self.pexels_api_key:
            print("⚠️ PEXELS_API_KEY is not configured.")
            return {
                **empty_result,
                "destination": destination,
                "message": (
                    "PEXELS_API_KEY is not configured. Add it to the "
                    ".env file to enable destination images."
                )
            }

        # --------------------------------------------------
        # SEARCH PEXELS
        # --------------------------------------------------
        query = f"{destination} travel destination"

        headers = {
            "Authorization": self.pexels_api_key
        }

        params = {
            "query": query,
            "orientation": "landscape",
            "size": "large",
            "per_page": self.pexels_image_count,
            "page": 1
        }

        try:
            response = requests.get(
                self.pexels_search_url,
                headers=headers,
                params=params,
                timeout=15
            )

            response.raise_for_status()
            data = response.json()

            photos = data.get("photos", [])

            images = []

            for photo in photos:
                if not isinstance(photo, dict):
                    continue

                src = photo.get("src", {})

                if not isinstance(src, dict):
                    continue

                image_url = (
                    src.get("large2x")
                    or src.get("large")
                    or src.get("landscape")
                    or src.get("medium")
                )

                if not image_url:
                    continue

                images.append({
                    "id": photo.get("id"),
                    "image_url": image_url,
                    "image_url_large": src.get("large2x"),
                    "image_url_medium": src.get("medium"),
                    "image_url_landscape": src.get("landscape"),
                    "pexels_url": photo.get("url"),
                    "photographer": photo.get("photographer"),
                    "photographer_url": photo.get(
                        "photographer_url"
                    ),
                    "alt": photo.get("alt") or destination
                })

            return {
                "available": bool(images),
                "destination": destination,
                "images": images,
                "attractions": [],
                "search_queries": [query],
                "image_count": len(images),
                "source": "Pexels",
                "source_url": "https://www.pexels.com/",
                "message": (
                    "Destination images loaded from Pexels."
                    if images
                    else "Pexels returned no matching images."
                )
            }

        except requests.exceptions.Timeout:
            print("⚠️ Pexels request timed out.")
            return {
                **empty_result,
                "destination": destination,
                "search_queries": [query],
                "message": "Pexels image request timed out."
            }

        except requests.exceptions.HTTPError as e:
            status_code = (
                e.response.status_code
                if e.response is not None
                else "unknown"
            )

            print(
                f"⚠️ Pexels API returned HTTP {status_code}."
            )

            return {
                **empty_result,
                "destination": destination,
                "search_queries": [query],
                "message": (
                    f"Pexels API returned HTTP {status_code}."
                )
            }

        except requests.exceptions.RequestException as e:
            print("⚠️ Pexels request failed:", str(e))
            return {
                **empty_result,
                "destination": destination,
                "search_queries": [query],
                "message": f"Pexels request failed: {str(e)}"
            }

        except (ValueError, TypeError) as e:
            print("⚠️ Invalid Pexels response:", str(e))
            return {
                **empty_result,
                "destination": destination,
                "search_queries": [query],
                "message": "Pexels returned an invalid response."
            }

        except Exception as e:
            print("⚠️ Unexpected Pexels error:", str(e))
            return {
                **empty_result,
                "destination": destination,
                "search_queries": [query],
                "message": f"Unexpected Pexels error: {str(e)}"
            }

    @staticmethod
    def _extract_destination(
        data: Any
    ) -> Optional[str]:
        """
        Recursively searches structured Planner output for a
        destination field.
        """

        if isinstance(data, dict):
            for key, value in data.items():
                normalized_key = (
                    str(key)
                    .strip()
                    .lower()
                    .replace("-", "_")
                    .replace(" ", "_")
                )

                if normalized_key == "destination":
                    if isinstance(value, str) and value.strip():
                        return value.strip()

            for value in data.values():
                result = Orchestrator._extract_destination(value)
                if result:
                    return result

        elif isinstance(data, list):
            for item in data:
                result = Orchestrator._extract_destination(item)
                if result:
                    return result

        return None

    @staticmethod
    def _extract_destination_from_text(
        text: str
    ) -> Optional[str]:
        """
        Last-resort destination extraction from the user's request.

        This does not depend on a destination dataset. The Planner Agent
        remains the primary source; these patterns are only a fallback.
        """

        if not isinstance(text, str):
            return None

        text = " ".join(text.strip().split())

        if not text:
            return None

        # Examples handled:
        #   trip to Ooty
        #   travel to Goa for 3 days
        #   visit Manali with friends
        #   vacation in Kerala
        #   from Chennai to Ooty for 2 people
        patterns = [
            r"\b(?:travel|trip|journey|go)\s+to\s+([^,.;!?]+?)(?=\s+(?:for|from|with|on|and)\b|$)",
            r"\bvisit\s+([^,.;!?]+?)(?=\s+(?:for|from|with|on|and)\b|$)",
            r"\bto\s+([^,.;!?]+?)(?=\s+(?:for|from|with|on|and)\b|$)",
            r"\b(?:vacation|holiday|stay)\s+in\s+([^,.;!?]+?)(?=\s+(?:for|from|with|on|and)\b|$)"
        ]

        for pattern in patterns:
            match = re.search(
                pattern,
                text,
                flags=re.IGNORECASE
            )

            if match:
                candidate = match.group(1).strip(" .,!?")
                if candidate:
                    return candidate

        # A common form: "from Chennai to Ooty".
        match = re.search(
            r"\bfrom\s+[^,.;!?]+?\s+to\s+([^,.;!?]+?)(?=\s+(?:for|with|on|and)\b|$)",
            text,
            flags=re.IGNORECASE
        )

        if match:
            candidate = match.group(1).strip(" .,!?")
            if candidate:
                return candidate

        return None

    @staticmethod
    def _normalize_text(
        value: Any
    ) -> str:
        """Normalizes text for safe case-insensitive comparison."""

        if not isinstance(value, str):
            return ""

        return " ".join(
            value.strip().lower().split()
        )


    # ======================================================
    # EXECUTE ONE AGENT
    # ======================================================

    def _execute_agent(
        self,
        agent_name: str,
        task: str,
        context: Dict[str, Any]
    ) -> Dict[str, Any]:

        try:

            agent = self.registry.create_agent(
                agent_name
            )

        except Exception as e:

            error_output = {
                "error": (
                    f"Could not create agent "
                    f"'{agent_name}': {str(e)}"
                )
            }

            self.memory.add_execution_record(
                agent=agent_name,
                task=task,
                status="failed",
                output=error_output
            )

            return {
                "agent": agent_name,
                "status": "failed",
                "task": task,
                "output": error_output
            }

        start_time = time.time()

        self.memory.add_execution_record(
            agent=agent_name,
            task=task,
            status="running"
        )

        try:

            result = agent.execute(
                task=task,
                context=context
            )

            execution_time = round(
                time.time() - start_time,
                3
            )

            if not isinstance(
                result,
                dict
            ):

                error_result = {
                    "error": (
                        f"{agent_name} returned "
                        "a non-dictionary result."
                    )
                }

                self._update_last_execution_record(
                    agent_name=agent_name,
                    status="failed",
                    output=error_result,
                    execution_time=execution_time
                )

                return {
                    "agent": agent_name,
                    "status": "failed",
                    "task": task,
                    "output": error_result,
                    "execution_time": execution_time
                }

            # --------------------------------------------------
            # IMPORTANT:
            # BaseAgent.execute() already provides status.
            # --------------------------------------------------

            status = result.get(
                "status"
            )

            raw_output = result.get(
                "output"
            )

            actual_output = self._unwrap_agent_output(
                raw_output
            )

            if status != "completed":

                self._update_last_execution_record(
                    agent_name=agent_name,
                    status="failed",
                    output=actual_output,
                    execution_time=execution_time
                )

                return {
                    "agent": agent_name,
                    "status": "failed",
                    "task": task,
                    "output": actual_output,
                    "execution_time": execution_time
                }

            if (
                isinstance(actual_output, dict)
                and "error" in actual_output
            ):

                self._update_last_execution_record(
                    agent_name=agent_name,
                    status="failed",
                    output=actual_output,
                    execution_time=execution_time
                )

                return {
                    "agent": agent_name,
                    "status": "failed",
                    "task": task,
                    "output": actual_output,
                    "execution_time": execution_time
                }

            self._update_last_execution_record(
                agent_name=agent_name,
                status="completed",
                output=actual_output,
                execution_time=execution_time
            )

            return {
                "agent": agent_name,
                "status": "completed",
                "task": task,
                "output": actual_output,
                "execution_time": execution_time
            }

        except Exception as e:

            execution_time = round(
                time.time() - start_time,
                3
            )

            error_result = {
                "error": (
                    f"{agent_name} execution failed: "
                    f"{str(e)}"
                )
            }

            self._update_last_execution_record(
                agent_name=agent_name,
                status="failed",
                output=error_result,
                execution_time=execution_time
            )

            return {
                "agent": agent_name,
                "status": "failed",
                "task": task,
                "output": error_result,
                "execution_time": execution_time
            }

    # ======================================================
    # UNWRAP AGENT OUTPUT
    # ======================================================

    @staticmethod
    def _unwrap_agent_output(
        output: Any
    ) -> Any:

        """
        Safely unwrap nested BaseAgent.execute()
        responses.

        Normal:

        {
            "request_analysis": ...,
            "subtasks": [...]
        }

        Wrapped:

        {
            "agent": "Planner Agent",
            "status": "completed",
            "output": {
                "request_analysis": ...,
                "subtasks": [...]
            }
        }

        Double wrapped:

        {
            "agent": "...",
            "status": "completed",
            "output": {
                "agent": "...",
                "status": "completed",
                "output": {...}
            }
        }
        """

        current = output

        max_unwraps = 5

        for _ in range(max_unwraps):

            if not isinstance(
                current,
                dict
            ):
                break

            nested_output = current.get(
                "output"
            )

            has_wrapper_fields = (
                "agent" in current
                or "status" in current
                or "execution_time" in current
            )

            if (
                has_wrapper_fields
                and nested_output is not None
            ):

                current = nested_output

            else:

                break

        return current

    # ======================================================
    # BUILD CONTEXT
    # ======================================================

    def _build_context(
        self
    ) -> Dict[str, Any]:

        context = self.memory.get_all()

        if not isinstance(
            context,
            dict
        ):

            context = {}

        context[
            "available_agents"
        ] = (
            self.registry
            .get_available_agents_for_planner()
        )

        if not context.get(
            "original_user_request"
        ):

            try:

                original_request = (
                    self.memory
                    .get_user_request()
                )

            except Exception:

                original_request = None

            if original_request:

                context[
                    "original_user_request"
                ] = original_request

                context[
                    "user_request"
                ] = original_request

        if not context.get(
            "destination_image_data"
        ):
            try:
                destination_image_data = (
                    self.memory.get(
                        "destination_image_data"
                    )
                )
            except Exception:
                destination_image_data = None

            if destination_image_data:
                context[
                    "destination_image_data"
                ] = destination_image_data

        return context

    # ======================================================
    # VALIDATE EXECUTION PLAN
    # ======================================================

    def _validate_execution_plan(
        self,
        subtasks: List[Dict[str, Any]]
    ) -> str | None:

        if not subtasks:

            return (
                "Planner Agent generated an "
                "empty execution plan."
            )

        step_numbers = set()

        # --------------------------------------------------
        # Validate subtasks
        # --------------------------------------------------

        for subtask in subtasks:

            if not isinstance(
                subtask,
                dict
            ):

                return (
                    "Planner generated an invalid "
                    "subtask."
                )

            required_fields = [
                "step",
                "task",
                "agent",
                "depends_on"
            ]

            for field in required_fields:

                if field not in subtask:

                    return (
                        f"Planner subtask is missing "
                        f"'{field}'."
                    )

            step = subtask["step"]

            if (
                isinstance(step, bool)
                or not isinstance(step, int)
            ):

                return (
                    "Planner step numbers must "
                    "be integers."
                )

            if step <= 0:

                return (
                    "Planner step numbers must "
                    "start from 1."
                )

            if step in step_numbers:

                return (
                    f"Duplicate Planner step: "
                    f"{step}."
                )

            step_numbers.add(
                step
            )

            agent_name = subtask["agent"]

            if (
                not isinstance(agent_name, str)
                or not agent_name.strip()
            ):

                return (
                    f"Step {step} has an "
                    "invalid agent name."
                )

            task = subtask["task"]

            if (
                not isinstance(task, str)
                or not task.strip()
            ):

                return (
                    f"Step {step} has an "
                    "invalid task."
                )

            dependencies = subtask[
                "depends_on"
            ]

            if not isinstance(
                dependencies,
                list
            ):

                return (
                    f"Step {step} has an invalid "
                    "'depends_on' field."
                )

        # --------------------------------------------------
        # Validate sequential steps
        # --------------------------------------------------

        expected_steps = set(
            range(
                1,
                len(subtasks) + 1
            )
        )

        if step_numbers != expected_steps:

            return (
                "Planner steps must be sequential "
                "starting from 1."
            )

        # --------------------------------------------------
        # Validate dependencies
        # --------------------------------------------------

        for subtask in subtasks:

            step = subtask["step"]

            dependencies = subtask[
                "depends_on"
            ]

            for dependency in dependencies:

                if (
                    isinstance(dependency, bool)
                    or not isinstance(
                        dependency,
                        int
                    )
                ):

                    return (
                        f"Step {step} contains an "
                        "invalid dependency."
                    )

                if dependency not in step_numbers:

                    return (
                        f"Step {step} depends on "
                        f"non-existing step "
                        f"{dependency}."
                    )

                if dependency >= step:

                    return (
                        f"Step {step} has invalid "
                        f"dependency {dependency}. "
                        "Dependencies must refer "
                        "to earlier steps."
                    )

                if dependency == step:

                    return (
                        f"Step {step} cannot "
                        "depend on itself."
                    )

        return None

    # ======================================================
    # CHECK DEPENDENCIES
    # ======================================================

    @staticmethod
    def _dependencies_completed(
        dependencies: List[Any],
        completed_steps: Dict[
            int,
            Dict[str, Any]
        ]
    ) -> bool:

        if not dependencies:

            return True

        for dependency in dependencies:

            if (
                isinstance(dependency, bool)
                or not isinstance(
                    dependency,
                    int
                )
            ):

                return False

            if dependency not in completed_steps:

                return False

        return True

    # ======================================================
    # VALIDATE AGENT OUTPUT
    # ======================================================

    @staticmethod
    def _is_valid_agent_output(
        output: Any
    ) -> bool:

        if output is None:

            return False

        if (
            isinstance(output, dict)
            and "error" in output
        ):

            return False

        return True

    # ======================================================
    # AGENT NAME → MEMORY KEY
    # ======================================================

    @staticmethod
    def _agent_context_key(
        agent_name: str
    ) -> str:

        mapping = {

            "Planner Agent":
                "planner_output",

            "Research Agent":
                "research_output",

            "Transportation Agent":
                "transportation_output",

            "Accommodation Agent":
                "accommodation_output",

            "Itinerary Agent":
                "itinerary_output",

            "Budget Agent":
                "budget_output",

            "Review Agent":
                "review_output",

            "Response Agent":
                "response_output"
        }

        if agent_name in mapping:

            return mapping[
                agent_name
            ]

        cleaned = (
            agent_name
            .lower()
            .replace(
                " agent",
                ""
            )
            .strip()
            .replace(
                " ",
                "_"
            )
        )

        if cleaned:

            return (
                f"{cleaned}_output"
            )

        return ""

    # ======================================================
    # UPDATE EXECUTION LOG
    # ======================================================

    def _update_last_execution_record(
        self,
        agent_name: str,
        status: str,
        output: Any,
        execution_time: float
    ):

        execution_log = getattr(
            self.memory,
            "_execution_log",
            []
        )

        if not execution_log:

            return

        for record in reversed(
            execution_log
        ):

            if (
                record.get("agent")
                == agent_name
                and record.get("status")
                == "running"
            ):

                record[
                    "status"
                ] = status

                record[
                    "output"
                ] = output

                record[
                    "execution_time"
                ] = execution_time

                break

    # ======================================================
    # GET ALL AGENT OUTPUTS
    # ======================================================

    def _get_agent_outputs(
        self
    ) -> Dict[str, Any]:

        outputs = {}

        for agent in self.registry.list_agents():

            if not isinstance(
                agent,
                dict
            ):
                continue

            agent_name = agent.get(
                "name"
            )

            if not agent_name:
                continue

            output = (
                self.memory.get_agent_output(
                    agent_name
                )
            )

            if output is not None:

                outputs[
                    agent_name
                ] = output

        return outputs

    # ======================================================
    # FAILURE RESPONSE
    # ======================================================

    def _failure_response(
        self,
        message: str,
        planner_output: Any = None,
        failed_agent: str | None = None,
        failed_step: int | None = None,
        agent_output: Any = None
    ) -> Dict[str, Any]:

        response = {

            "success": False,

            "error": message,

            "destination_image_data": (
                self.memory.get("destination_image_data")
                or {}
            ),

            "agent_outputs": (
                self._get_agent_outputs()
            ),

            "execution_log": (
                self.memory
                .get_execution_log()
            )
        }

        if planner_output is not None:

            response[
                "planner_output"
            ] = planner_output

        if failed_agent is not None:

            response[
                "failed_agent"
            ] = failed_agent

        if failed_step is not None:

            response[
                "failed_step"
            ] = failed_step

        if agent_output is not None:

            response[
                "agent_output"
            ] = agent_output

        return response